// src/pages/AIInsights.jsx
import { useState, useEffect } from "react";
import Card, { SectionTitle } from "../components/Card";
import { C } from "../data/constants";
import { getInsights, getAnomalies } from "../data/api";

export default function AIInsights({ expiry }) {
  const [markdown,  setMarkdown]  = useState("");
  const [anomalies, setAnomalies] = useState([]);
  const [loading,   setLoading]   = useState(true);
  const [shown,     setShown]     = useState([]);

  useEffect(() => {
    setLoading(true);
    Promise.all([getInsights(expiry), getAnomalies(expiry)])
      .then(([ins, anom]) => {
        setMarkdown(ins.markdown || "No insights available.");
        setAnomalies(anom);
        // Stagger anomaly card reveal
        anom.forEach((_, i) => setTimeout(() => setShown(p => [...p, i]), i * 220 + 300));
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [expiry]);

  const sevColor = (score) => score < -0.3 ? C.red : score < 0 ? C.amber : C.cyan;

  return (
    <div style={{ display:"flex", flexDirection:"column", gap:16 }}>

      {/* AI Markdown Summary — from generate_insights() */}
      <Card delay={0} accent={C.green}>
        <SectionTitle accent={C.green}>AI MARKET SUMMARY — GENERATED BY BACKEND</SectionTitle>
        {loading ? (
          <div style={{ display:"flex", alignItems:"center", gap:10, color:C.textDim, fontSize:12 }}>
            <div style={{ width:16, height:16, border:`2px solid ${C.green}30`, borderTop:`2px solid ${C.green}`, borderRadius:"50%", animation:"spin 0.8s linear infinite" }} />
            Generating insights...
            <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
          </div>
        ) : (
          <div style={{ fontSize:13, color:"#cbd5e1", lineHeight:1.8, whiteSpace:"pre-wrap" }}>
            {/* Render markdown as plain text — install react-markdown for proper rendering */}
            {markdown}
          </div>
        )}
      </Card>

      {/* Anomaly Detection Results — from detect_anomalies() + Isolation Forest */}
      <Card delay={100} accent={C.red}>
        <SectionTitle accent={C.red}>ANOMALY DETECTION — ISOLATION FOREST OUTPUT ({anomalies.length} FLAGGED)</SectionTitle>
        {loading && <div style={{ color:C.textDim, fontSize:12 }}>Loading anomalies...</div>}
        {!loading && anomalies.length === 0 && (
          <div style={{ color:C.textDim, fontSize:12 }}>No anomalies detected for this expiry.</div>
        )}
        <div style={{ display:"flex", flexDirection:"column", gap:10, marginTop: anomalies.length > 0 ? 8 : 0 }}>
          {anomalies.map((a, i) => {
            const color = sevColor(a.anomaly_score);
            return (
              <div key={i} style={{
                background: "#060f08", border:`1px solid ${color}22`, borderLeft:`4px solid ${color}`,
                borderRadius:8, padding:"14px 18px",
                opacity: shown.includes(i) ? 1 : 0,
                transform: shown.includes(i) ? "translateX(0)" : "translateX(-24px)",
                transition: "opacity 0.4s ease, transform 0.4s ease",
              }}>
                <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:8 }}>
                  <div style={{ display:"flex", gap:8, alignItems:"center" }}>
                    <span style={{ background:`${color}15`, border:`1px solid ${color}40`, color, borderRadius:4, padding:"2px 8px", fontSize:9, letterSpacing:1 }}>ANOMALY</span>
                    <span style={{ background:`${color}10`, color, borderRadius:4, padding:"2px 6px", fontSize:9 }}>
                      Score: {a.anomaly_score.toFixed(4)}
                    </span>
                  </div>
                  <span style={{ fontSize:10, color:C.textDim }}>{a.datetime.slice(0,16).replace("T"," ")} IST</span>
                </div>
                <div style={{ display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:8, marginTop:6 }}>
                  {[
                    ["Strike",  a.strike],
                    ["CE Vol",  `${(a.volume_CE/1000).toFixed(0)}K`],
                    ["PE Vol",  `${(a.volume_PE/1000).toFixed(0)}K`],
                    ["CE OI",   `${(a.oi_CE/100000).toFixed(2)}L`],
                  ].map(([k,v]) => (
                    <div key={k} style={{ background:"#0a1a0f", borderRadius:4, padding:"6px 10px" }}>
                      <div style={{ fontSize:8, color:C.muted, letterSpacing:1 }}>{k}</div>
                      <div style={{ fontSize:12, color:"#e2e8f0", marginTop:2 }}>{v}</div>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </Card>

    </div>
  );
}